extends:
  - "@commitlint/config-conventional"
rules:
  header-max-length:
    - 1
    - "always"
    - 50
  body-max-line-length:
    - 1
    - "always"
    - 72
  footer-max-line-length:
    - 1
    - "always"
    - 72
  type-enum:
    - 2
    - always
    - - ci
      - feat
      - fix
      - docs
      - style
      - refactor
      - chore
      - release
