[package]
name = "concurrency"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1.45", features = ["rt-multi-thread", "macros", "time"] }

[dev-dependencies]
